Documentation page
jeetsdev/Sudo-UI pull request #2
Opened 2022-01-31 17:46 UTC by jeetsdev

Added documentation page for components.

2022-01-31 17:53 UTC, shraddha15-creator requested changes

2022-01-31 17:53 UTC, shraddha15-creator commented on css/docs.css
> +    /* outline: 1px solid green; */
remove commented code and empty lines

2022-01-31 18:08 UTC, jeetsdev commented on css/docs.css
> +    /* outline: 1px solid green; */
Removed that.

2022-01-31 18:34 UTC, shraddha15-creator approved these changes

2022-02-01 04:16 UTC, pritam-kr approved these changes

2022-02-01 04:18 UTC, merged